config/routes.rb
Rails.application.routes.draw do
  get 'favorites/update'

  devise_for :users
  root 'posts#index'

  resources :favorites
  resources :posts do 
  resources :comments, only: [:create, :destroy]
  end
  resources :likes, only: [:create, :destroy ]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :post
   # belongs_to :user
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
  # validates :user_id, uniqueness: { scope: :post_id }
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :comments, dependent: :destroy 
    has_many :likes
    has_many :favorites
    validates :title, presence: true, length: { minimum: 10 }
    validates :content, presence: true, length: { minimum: 10 }
end

app/models/user.rb
class User < ApplicationRecord
 has_many :likes
#  has_many :comments
 has_many :posts
 has_many :favorites
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!

    def favorite_text 
    return @favorite_exists ? "💔Unfavorite" : "🧡Favorite"
    end

    helper_method :favorite_text
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def create
        @post = Post.find(params[:post_id])
        @comment = @post.comments.create(params[:comment].permit(:name, :comment))
         redirect_to post_path(@post)    
    end
  
    def destroy
        @post = Post.find(params[:post_id])
        @comment = @post.comments.find(params[:id])
        @comment.destroy
        redirect_to post_path(@post)
    end
  
  end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def index
   
end
  def update
    favorite = Favorite.where(post:Post.find(params[:post]), user: current_user)
    if favorite == []
      Favorite.create(post: Post.find(params[:post]), user: current_user)
     @favorite_exists = true
    else
favorite.destroy_all
@favorite_exists = false
    end
    respond_to do |format|
      format.html {}
    end
  end

 
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

    def create
        
   @like = current_user.likes.new(like_params)
   if !@like.save
    flash[:notice] = @like.errors.full_messages.to_sentence
   end
   redirect_to @like.post
    end

    def destroy
        @like = current_user.likes.find(params[:id])
        post = @like.post
        @like.destroy
        redirect_to post
    end

    private

    def like_params
        params.require(:like).permit(:post_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController 



def favourite 
end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController 


    def index
        @posts = Post.all
    end

  def new
    @post = Post.new
end

def edit
    @post = Post.find(params[:id])
end

def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
        flash[:notice] = "Post was created successfully"
        redirect_to @post
    else
        render 'new'
    end
end

def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
        flash[:notice] = "post was updated successfully"
        redirect_to @post
    else
        render 'edit'
    end
end

def show
    @post = Post.find(params[:id])
   @favorite_exists = Favorite.where(post: @post, user: current_user) == [] ? false : true

end



def destroy
    @post = Post.find(params[:id])
    @post.destroy
   redirect_to root_path

end

private

def post_params
    params.require(:post).permit(:title, :content)
end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/comments/_comment.html.erb
<div class="box">

<p><strong>by <%= comment.name %>:</strong>
              <%= comment.comment %>
</p><br>
<%= link_to 'Delete', [comment.post, comment], data: { turbo_confirm: "are you sure?",turbo_method: :delete } %>


</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build], local: true) do |f| %>
  <p>
      <%= f.label :name %><br>
      <%= f. text_field :name %>
  </p>
 
  <p>
  <%= f.label :comment %><br>
  <%= f. text_area :comment %>
</p>
<p>
<%= f.submit %>
<p>
<% end %>

app/views/favorites/index.html.erb
<h3> listing the favorites posts </h3>
     <% current_user.favorites.each do |favorite| %>



      You favorited this post: <%= link_to favorite.post.title,favorite.post %>
   
   
   
      <br>
   
   
   
      <% end %>

app/views/favorites/update.js.erb
$('#favorite_link').text(<%= "favorite_text %>");

app/views/layouts/_messages.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg bg-light">
 <div class="container-fluid">
 <a class="navbar-brand" href="#">Blog-App</a>
 <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
 <span class="navbar-toggler-icon"></span>
 </button>
 <div class="collapse navbar-collapse" id="navbarSupportedContent">
 <ul class="navbar-nav me-auto mb-2 mb-lg-0">
 <li class="nav-item">
 <%= link_to 'Posts', root_path, class: "nav-link active" %>
 </li>
 <li class="nav-item">
 <%= link_to "Create New Post", new_post_path, class:"nav-link" %></a>
 </li>
 <li class="nav-item dropdown">
 <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 Dropdown
 </a>

 <ul class="dropdown-menu">
 <li>
 <%= link_to 'Favorites', favorites_path, class:"dropdown-item" %>
 </li>

 
 <li>
 <%= link_to 'Sign out',destroy_user_session_path, data: {  turbo_method: :delete },class:"dropdown-item" %>
</li>
 
 </ul>
 </li>

 </ul>

 </div>
 </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogDemo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>


<%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="d-flex flex-column">

<%= render 'layouts/navigation' %>
<div class="container">
       <%= render 'layouts/messages' %>
        <%= yield %>
</div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="jumbotron">
  <h1 class="display-4">Hello, world!</h1>
  <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
  <hr class="my-4">
  <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
  <p class="lead">
    <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
  </p>
</div>
<%= link_to 'Sign out', destroy_user_session_path, data: {  turbo_method: :delete } %>
<footer id="sticky-footer" class="py-4 bg-dark text-white">
  <div class="container text-center">
    <small>Copyright &copy; Your Website</small>
  </div>
</footer>

app/views/posts/_form.html.erb
<% if @post.errors.any? %>
<h2> The following errors prevented the post being saved </h2>
<ul>
<% @post.errors.full_messages.each do |msg| %>
   <li><%= msg %></li>
   <% end %>
   </ul>
   <% end %>
<%= form_with scope: :post, url: posts_path, local: true do |f| %>
   <p>
       <%= f.label :title %><br>
       <%= f. text_field :title %>
   </p>
  
   <p>
   <%= f.label :content %><br>
   <%= f. text_area :content %>
</p>
<p>
<%= f.submit %>
<p>
<% end %>

app/views/posts/edit.html.erb
<h1> edit the post</h1>

<% if @post.errors.any? %>
<h2> The following errors prevented the post being saved </h2>
<ul>
<% @post.errors.full_messages.each do |msg| %>
   <li><%= msg %></li>
   <% end %>
   </ul>
   <% end %>
<%= form_with(model: @post, local: true) do |f| %>
   <p>
       <%= f.label :title %><br>
       <%= f. text_field :title %>
   </p>
  
   <p>
   <%= f.label :content %><br>
   <%= f. text_area :content %>
</p>
<p>
<%= f.submit %>
<p>
<% end %>

app/views/posts/index.html.erb
<h1> Listing all posts </h1>
<div class="container">
<table>
        <thead>
            <tr>
            <th>title</th>
            <th>content</th>
            <th>Action</th>
            </tr>
        </thead>
                <tboby>
                 <% @posts.each do |post| %>
                        <tr>
                        <td><%= post.title %></td>
                        <td><%= post.content %></td>
                        <td><%= link_to "Edit", edit_post_path(post), class:"button" %></td>
                        <td><%= link_to "Delete", post_path(post), data: { turbo_confirm: "Are you sure?", turbo_method: :delete } %></td>
                        <td><%= link_to "Show", post_path(post), class:"button" %></td>
                        <td><%= post.comments.count %>comments</td>   
                        <td><%= post.likes.count %>likes</td>
                        <td> by <%= post.user.email %></td>            
                      </tr>
                    <% end %>
                </tbody>
                
     </table>
     
   </div>  

app/views/posts/new.html.erb
<h1> Create new post </h1>
<%= render 'form' %>

app/views/posts/show.html.erb
<h1> Showing post</h1>
<div class="container">
<p> by <%= @post.user.email %></p>
<p><strong>Title:<%= @post.title %></strong></p>
<p><strong>Content:<%= @post.content %></strong></p>

<%= link_to favorite_text,favorites_update_path(post: @post), id:'favorite_link', remote: true %>||

<%= link_to "Edit", edit_post_path(@post), class:"button" %>||
<%= link_to "Delete", post_path(@post), data: { turbo_confirm: "Are you sure?", turbo_method: :delete } %>

<p><strong><%= @post.likes.count %></strong> likes</p>
<% like = current_user.likes.find_by(post: @post) %>
<% if like.nil? %>
<form action="/likes" method="post">
<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
<input type="hidden" name="like[post_id]" value="<%= @post.id %>">
<input type="submit" value="👍">
</form>

<% else %>

<form action="<%= like_path(like) %>" method="post">
<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
<input type="hidden" name="_method" value="Delete" >
<input type="submit" value="👎">
</form>
<% end %>

<p><strong><%= @post.comments.count %></strong> Comments</p>
 <%= render @post.comments %>
 <h3>Leave a reply</h3>
<%= render 'comments/form' %>
</div>